name: Format on merge

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORMATTING_TOKEN }}

      - name: Set up mise
        uses: jdx/mise-action@v2
        with:
          cache: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fix code formatting
        run: pnpm format

      - name: Commit formatting fixes
        run: |
          git config --local user.email "action@github.com"
          git config --global user.name 'github-actions[bot]'
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-fix formatting"
            git push
          fi
